name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate image tag
      run: |
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
        echo "image_tag=${{ secrets.DOCKERUSER }}/backstage:$SHORT_SHA" >> "$GITHUB_ENV"
    - name: Build the Docker image
      run: docker build . --tag $image_tag
    - name: Login to DockerHub
      run : docker login -u ${{ secrets.DOCKERUSER }} -p ${{ secrets.DOCKERPASS }}
    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKERUSER }}/$image_tag
