name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      image_tag: backstage:$(date +%s)
    steps:
    - uses: actions/checkout@v4
    - name: Generate image tag
      run: echo "tag=backstage:$(date +%s)" >> "$GITHUB_OUTPUT"
    - name: Build the Docker image
      run: docker build . --tag jerinpaul/$image_tag
    - name: Login to DockerHub
      run : docker login -u ${{ secrets.DOCKERUSER }} -p ${{ secrets.DOCKERPASS }}
    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKERUSER }}/$image_tag
